// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 4171964
#define UNITY_VERSION_UNDER_HASH "6000.3.5f2_3fa8bc678cb0"
#define UNITY_VERSION_PARENS_HASH "6000.3.5f2 (3fa8bc678cb0)"
#define UNITY_VERSION_WIN "6000.3.5.4171964"
